### ISSUE TITLE
Request/discussion: HA sensor should show time, not relative time

### ISSUE THREAD

**Issue by vingerha** [mark1foley/ha-gtfs-rt-v2#18]
Hi Mark, 
I am living in France and my main bus-provider recently changed the RT from json to protobuf, requireing me to review other solutions as json I can handle. 
I found zacs version which was a bit old and then your fork of it. I have a few questions to determine where I go
To begin with: your solution works fine, so **thanks** for that !

1. vehicle position url does not seem to be 'optional', i.e. if I leave it out then I get errors
2. how can I verify if my provider show lat/lon in the veh-position url? The log shows 'not defined' but not 100% sure this is correct as the source may be incorrect too. I decomposed the bin with 'transit_realtime.FeedMessage'  and could not find a thing so maybe this is indeed missing? EDIT: also checked with VehiclePosition
3. Personally I would prefer that the state shows datetime and not relative time, this would allow HA users to do whatever they want. i.e. by giving it s class 'timestamp' the entity card would show relative time by default. It is also more (lets call it) standard HA
4. EDIT: can there be a different interval? It now seems to poll a lot and I donot require this, usually only between 7:00 and 9:00 and 16:00-18:00. Trying to reduce unnecessary bandwidth usage. Polling between set-times can be done via automations but then the 'interval' for the main sensor has to be set to 'hours'
5. EDIT: how does this behave if I add multiple sensors, would it run per-sensor vs. the source gtfs url?
6. Are you planning to add this to HA as a core element or HACS? If not, why...just interested in your thinking? 
Thanks
Arjan

**Comment by corneels** [comment]
Arjan, could you post some links to your bus provider RT data?

**Comment by vingerha** [comment]
Hi, this is the only (!) link for this particular provider, with 'trip-update' at the end I guess this sort-off says it all
https://proxy.transport.data.gouv.fr/resource/region-sud-gtfs-rt-trip-update

The overall site
https://trouver.datasud.fr/dataset/lignes-des-reseaux-de-transport-zou-en-regionsud

**Comment by mark1foley** [comment]
Hi,
Apologies for the delayed response - it's hard to get to this stuff during the week.  In answer to your questions:

1. The vehicle update is meant to be option but this was inadvertently broken by a recent code update.  The bug has been fixed and included in the next release.  In the mean time you can use vehicle_position_url: '' to get around the problem.
2. I have looked at the data returned by your provided and I believe they are not provided vehicle position data.  
3. I'm not sure what you mean by "relative time".  I guess this means you would prefer the sensor state to be set to the date/time the service is due rather than an integer container the number of minutes until it arrives.  I can kind of see the logic but I think that users find both values useful.  There is already an attribute called 'Due at' that shows the time due in 24-hour format.  Could you not be used to meet your needs?
4. I will consider your suggestion to throttle the request frequency based on the time of day.  But to be honest I don't see it as a high priority as I believe the bandwidth used by the integration is pretty small in the scheme of things (each update less that 1MB on average).  But if other see value in this then would be happy to re-assess.
5. If multiple services are defined then they will be updated by a single call to the transport provider for trip and vehicle position data.  Does this answer your question?
6. I think the integration as it is written has some limitations.  It would be much more useful if it combined the static scheduling information with the realtime data.  This would solve a number of issues raised here already.   I'm not sure of the process of how or why an integration becomes part of the HA core.  I guess it would need to be pretty popular for that to happen.  Regardless, the support would still come back to this forum so I don't see a lot of change.

Hope that helps.

Mark

**Comment by vingerha** [comment]
Hi, thanks for the feedback and thinking.
My, and I guess most people's, challenge is the yaml stuff including digging into the gtfs data to understand which route etc. In that sense it would be good to have the static gtfs integrated and possibly select the stops from the GUI, this is a lot of work though and for me outside of the available dev competency (am not a dev). If you have any idea on how to GUI-select the stops/routes from the sqlite gtfs db then maybe I can look at that too.

Wrt to the state value, as you may see in my new version (link above), I already built-in the datetime instead of minutes, I prefer to have a datetime instead of a float/integer indicating minutes. A use case is the poor quality from my provider where I would like to see the actual time and not a calculation, to review if the data is correct,... of course one should normally not have to worry about the data quality but it is as it is with this one.
I also thought about my comment on the frequency and will probably build it in, the main reason: our bus's frquency is 30m or 1h and no point in collecting data every minute, the only trick I see is to find out when to trigger it. As it can not be too short to the actual departire time neither to far off.....the dev work is a small thing but possibly a waste of time in the end :)
Cheers
Arjan

**Comment by vingerha** [comment]
Closing this issue, I have create a combined GTFS and GTFS-realtime thingy for HACS, based on GTFS-core and your integration. I will gradullay progress with getitng to what I (believe) want :)
