### ISSUE TITLE
Integration not showing up under Configuration

### ISSUE THREAD

**Issue by FSTGuy** [mark1foley/ha-gtfs-rt-v2#3]
Hi Mark,

Your integration looks great. I am having an issue with the install and was hoping you could help me. I was able to download your repository through HACS, checked and configuration is valid and restarted HA. When I try to search for the integration under Configuration -> Devices & Services the integration does not show up. I would be interested in your thoughts.

Configuration information
- Home Assistant 2022.4.4 
- I have added the sensor configuration into a sensor.yaml. My configuration.yaml file has the !include sensor.yaml

**Comment by FSTGuy** [comment]
Hi Mark,

I was able to resolve the issue. The trip update URL was not correct. I updated the URL.

The sensors are available. It appears they are not able to pick up the time from GTFS feeds.

The error from the log is here.
https://pastebin.com/XweeQPKx

I have upgraded to 2022.4.5 and still encounter the error. I would be interested in your thoughts.

**Comment by mark1foley** [comment]
Hi,
Unfortunately, there is very little consistency in implementation in this GTFS real-time world.  Even though the routes.txt file for Calgary specifies the route ID as "201-20659" in the real-time feed the Route ID is just "201".  The sensors were not being updated due to this mismatch.  If you change the route in your sensor.yaml file from 201-20659 to just 201 I believe it will work fine.
Regards,
Mark

**Comment by FSTGuy** [comment]
Hi Mark,

Thank you, that was the issue. Interesting, only the first portion of the route ID is used. I really appreciate you taking the time to investigate and reply! I am now able to get the train times.

Thanks again!
